version: "3.3"

services:
  zinfurn-api:
    container_name: zinfurn-api
    restart: always
    image: node:20.10.0
    ports:
      - 4001:3007
    volumes:
      - ./:/usr/src/zinfurn
    working_dir: /usr/src/zinfurn

    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod"

  zinfurn-batch:
    container_name: zinfurn-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - 4002:3008
    volumes:
      - ./:/usr/src/zinfurn
    working_dir: /usr/src/zinfurn

    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge

# nestar-next: localhost:5000 <==> container:3000
# nestar-api: localhost:5001 <==> container:3007
# nestar-next: localhost:5002 <==> container:3008